"""Generate a real worked example for the SKM blog from scored actions.

Finds an actual high-difficulty, high-context, positive-ΔP pass under
pressure late in a close game, plus a routine comparison pass, and writes
docs/WORKED_EXAMPLE.md with the real component values — replacing the
blog's hypothetical example, per the build plan ("take a single real
possession from StatsBomb open data").
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from skm.config import (  # noqa: E402
    ACTIONS_SCORED_PARQUET,
    DATA_PROCESSED,
    GAMES_PARQUET,
    SKM_W_C,
    SKM_W_D,
    SKM_W_R,
)


def _fmt_row(r, names, games):
    game = games[games["game_id"] == r["game_id"]].iloc[0]
    minute = (int(r["period_id"]) - 1) * 45 + r["time_seconds"] / 60.0
    player = names.get(r["player_id"], f"player {int(r['player_id'])}")
    skm_check = r["delta_p"] * (1 + SKM_W_D * r["D"] + SKM_W_C * r["C"] + SKM_W_R * r["R"])
    return {
        "player": player,
        "match": f"{game['competition']} {game['season']}, game {int(r['game_id'])}",
        "minute": f"{minute:.0f}'",
        "pressure": bool(r["under_pressure"]),
        "delta_p": r["delta_p"],
        "D": r["D"],
        "C": r["C"],
        "R": r["R"],
        "skm": r["skm"],
        "skm_check": skm_check,
        "position_weight": r.get("position_weight", 1.0),
        "role_weight": r.get("role_weight", 1.0),
        "game_state_weight": r.get("game_state_weight", 1.0),
        "sequence_weight": r.get("sequence_weight", 1.0),
        "adjusted_skm": r.get("adjusted_skm", r["skm"]),
    }


def main() -> int:
    import socceraction.spadl as spadl

    actions = pd.read_parquet(ACTIONS_SCORED_PARQUET)
    games = pd.read_parquet(GAMES_PARQUET)
    names = (
        pd.read_parquet(DATA_PROCESSED / "player_names.parquet")
        .set_index("player_id")["player_name"]
        .to_dict()
    )

    named = spadl.add_names(actions)
    named["minute"] = (named["period_id"] - 1) * 45 + named["time_seconds"] / 60.0
    passes = named[
        (named["type_name"] == "pass")
        & (named["result_name"] == "success")
        & named["delta_p"].notna()
    ].copy()
    passes["forward"] = (passes["end_x"] - passes["start_x"]).abs()

    # The key moment: late, under pressure, hard, valuable
    key = passes[
        passes["under_pressure"].astype(bool)
        & (passes["minute"] >= 70)
        & (passes["delta_p"] > 0.02)
        & (passes["forward"] >= 15)
    ].sort_values(["D", "C"], ascending=False)
    key_row = key.iloc[0]

    # The routine contrast: early, no pressure, easy, same positive ΔP band
    routine = passes[
        (~passes["under_pressure"].astype(bool))
        & (passes["minute"] <= 30)
        & (passes["delta_p"].between(key_row["delta_p"] * 0.8, key_row["delta_p"] * 1.2))
        & (passes["D"] <= passes["D"].quantile(0.3))
    ].sort_values("C").iloc[0]

    k, r = _fmt_row(key_row, names, games), _fmt_row(routine, names, games)

    def table(d):
        return (
            f"| Component | Value | \n|---|---|\n"
            f"| ΔP (VAEP) | {d['delta_p']:+.4f} |\n"
            f"| D (difficulty) | {d['D']:.2f} |\n"
            f"| C (context) | {d['C']:.2f} |\n"
            f"| R (role) | {d['R']:.2f} |\n"
            f"| **SKM v1** = ΔP × (1 + 0.3D + 0.3C + 0.3R) | **{d['skm']:+.4f}** |\n"
            f"| Position / role / game-state / sequence weights | "
            f"{d['position_weight']:.2f} / {d['role_weight']:.2f} / "
            f"{d['game_state_weight']:.2f} / {d['sequence_weight']:.2f} |\n"
            f"| **Adjusted SKM (v1.5)** | **{d['adjusted_skm']:+.4f}** |\n"
        )

    ratio = k["skm"] / r["skm"] if r["skm"] else float("nan")
    adj_note = ""
    if r["adjusted_skm"] > k["adjusted_skm"]:
        adj_note = (
            "\nNote the v1.5 adjusted layer *narrows or flips* this particular "
            "comparison: the routine pass was progressive for the passer's "
            "position and fed a chain ending in a shot, so its position and "
            "sequence weights lift it. Both effects are visible in the "
            "decomposition above — that transparency is the design goal, and "
            "it is exactly the kind of interaction a single black-box number "
            "would hide.\n"
        )
    md = f"""# Worked example (real data)

Generated by `scripts/worked_example.py` from the scored open-data sample —
no hypothetical numbers. Every value below is a model output on a real
StatsBomb open-data action.

## The key moment

**{k["player"]}** — {k["match"]}, {k["minute"]}, successful forward pass
under pressure.

{table(k)}

## The routine contrast

**{r["player"]}** — {r["match"]}, {r["minute"]}, successful pass with no
pressure, similar raw ΔP ({r["delta_p"]:+.4f} vs {k["delta_p"]:+.4f}).

{table(r)}

## The point

Two passes with nearly identical downstream value (ΔP): SKM v1 scores the
pressured, late, difficult one **{ratio:.1f}×** higher. That gap — invisible
to pure outcome metrics — is what SKM is for.
{adj_note}

*Caveats: D/C/R are v1 models on event data only (no tracking); "line-
breaking" cannot be verified without defender positions, so selection used
forward distance + pressure as proxies.*
"""
    out = Path(__file__).resolve().parents[1] / "docs" / "WORKED_EXAMPLE.md"
    out.write_text(md, encoding="utf-8")
    print(md)
    print(f"→ wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
